### ISSUE TITLE
Fix Feature: "Associate List" tab when logged in as a Trainer (populate list and implement search functionality)

### ISSUE THREAD

**Issue by Wu-Kevin** [revaturelabs/trackforce#656]
As a Trainer, under the "Associate List" tab, any text input into "Search by Text" only modifies the First and Last Name columns rather than Marketing Status/Client, etc.

**Comment by MTichael** [comment]
The original issue has been resolved: the search feature now reorganizes all table columns. 

"Search by Name" will search the first and last name separately, so 'sam' matches any name that has 'sam' in it, like Samuel or Haisam, be it first or last name. However, 'Samuel Wood' matches nothing, because there is no first name or last name that matches that string. I.E. the search function should be altered to separate input string by spaces and search the respective fields or else the label for the field should be changed to reflect the true nature of the search option. 
The "Status" search menu will search by marketing status, but there is also a field called 'Verification Status'. This is misleading; the header for the search field should at least be fixed to clear up ambiguity.

**Comment by suttergrune** [comment]
Full name search has been enabled. It's now possible to search by first name only, last name only, or both first name and last name together.
