### ISSUE TITLE
Interview tab automatically sends user back to home page

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#785]
Steps to reproduce: 
1. Login as Associate
2. Click Interview tab
3. Get sent back to home page

Dirty fix: uncomment the "location.reload" line at the end of the updateInterviews method

**Comment by huangl6** [comment]
me

**Comment by csiu13** [comment]
So, if you open Chrome dev tools and go to the Networks tab while recreating this bug, you may notice that every time you try to open the Interviews tab, another set of OPTIONS and GET requests for the interviews is tagged on. For example, the first time you try to access the interviews tab, the name of the requests will go as follows:
5
0
clients
5
0
clients
0
0
5
0
0
5
5 being the request for the associate, 0 being the request for the interview, and client being the request for the list of clients. The next time will look like following the 5, 0, client chain:
0
0
0
5
0
0
0
5
You may notice they come in pairs. Thats because the first groups of 0 0 0 5 is OPTIONS request and the next 0 0 0 5 is GET. But the main thing to note is that another pair of OPTIONS and GET requests are tagged on. I'm not sure why this happens but this pattern continues until the page is refreshed. I honestly think that the reason for the page returning is the 5 (aka the associate) request but none of this happens when you refresh the page. Good luck to whoever takes this problem up
Message Input

Message @Vivi Vo

**Comment by wfparrish** [comment]
The issue disappeared after the modularization of the software
