### ISSUE TITLE
Anyone can become an admin by modifying local storage role

### ISSUE THREAD

**Issue by KevCrisanto** [revaturelabs/trackforce#791]
Steps:
- Login as an associate
- Go to Developer Tools -> Application -> Local Storage.  Change the user role to admin (1)
- Refresh the page. 
- Create an admin account.
- Login using the created account to verify it worked.

**Comment by MrDetail56000** [comment]
This issue hilights an underlying vulnerability in the web service. Some resources rely on incomming JSON data for authentication rather than the JWT token system already in place.  Things that need to be changed in order to secure the web service:

UserResource.java - The methods createUser, createNewAssociate and createTrainer all trust the incomming JSON data which can easily be forged by a malicious user.  They should be changed to only accept user provided parameters such as name and password.  Also, there is no verification of data on the backend; it is solely reliant on frontend verificatoin.

AssociateService.java - The method createAssociate seems as if it were written as a last minute workaround to get the project presentation ready. This method needs to create new associates and users, not rely on those passed in via JSON.

Pull request #790 fixes the vulnerability but this is only a workaround, the origin of the problem still exists.

**Comment by Bioshock667** [comment]
@werlej  and I found that some HTTP requests with the forged identification such as _GET /associates/countAssociates_ are allowed to run.  Joe has updated the Jersey API so that two paths _POST users/newUser_ and _GET associates/countAssociates_ verify the user's role through their token.

This change results in the following.  After user changes his role and refreshes homepage.  It asks to login with navbar button rendered inactive. 

Every endpoint must be verified to check admin privilege through token if necessary.

**Comment by Bioshock667** [comment]
Once frontend implements a service that verifies its status before every request, this issue can be closed.
