### ISSUE TITLE
Illegal access issue 

### ISSUE THREAD

**Issue by davidcheng1760** [revaturelabs/trackforce#930]
![image](https://user-images.githubusercontent.com/42741091/47873824-98c50500-dde8-11e8-9e3b-54f78f86ee68.png)

**Comment by MussabElDash** [comment]
add a contextListener that starts when the server starts and destroys… with it.

This pull request is for issues #687 and #930 Which I'm 90% sure they're the same issue

And added in the destroy method code to force turning off the hibernate resources in order to prevent memory leak Exception:
C3P0PooledConnectionPoolManager

and in addition to that I added export JAVA_OPTS="-Dfile.encoding=UTF-8 -Xms128m -Xmx1024m -XX:PermSize=64m -XX:MaxPermSize=256m" in $CATALINA_HOME/bin/setenv.sh in order to increase the memory used and also used as way to prevent memory leak

**Comment by lukasmckela** [comment]
This appears to be resolved as per previous comment/commit.
